package com.kharitonov.gym.model.validator;

public enum ValidationError {
    LOGIN_EXISTS,
    EMAIL_EXISTS,
    APPLICATION_EXISTS,
    INVALID_LOGIN_FORMAT,
    INVALID_PASSWORD_FORMAT,
    INVALID_NUMBER_FORMAT,
    INVALID_EMAIL_FORMAT,
    PASSWORDS_ARE_NOT_EQUAL,
    WRONG_LOGIN_PASSWORD,
    LOW_BALANCE
}
